defaults: &defaults
  adapter: postgres
  username: postgres
  password:
  host: localhost

test:
  <<: *defaults
  database: tvrss_test

development:
  <<: *defaults
  database: tvrss_dev

production:
  <<: *defaults
  database: tvrss
  host: db-server-01
