production:
  domain:
  - name: "philip@ivercore.com"
    ssh_options:
    - "-p 2901"
  deploy_to: "/var/www/tvrss.ivercore.com/"
  repository: "git@github.com:philly-mac/tvrss.git"
  post_setup_script: "bin/post-setup.sh"
  post_deploy_script: "bin/post-deploy.sh"
  branch: "deploy"
  rake_env:
    RAILS_ENV: "production"
    DEPLOY_DIR: "tvrss.ivercore.com"
    DEPLOY_USER: "philip"
    DEPLOY_GROUP: "www-data"

